//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 05:46:49 PM CET 
//


package pandadomain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}atomic"/>
 *         &lt;element ref="{}not"/>
 *         &lt;element ref="{}and"/>
 *         &lt;element ref="{}or"/>
 *         &lt;element ref="{}imply"/>
 *         &lt;element ref="{}forall"/>
 *         &lt;element ref="{}exists"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "atomicOrNotOrAnd"
})
@XmlRootElement(name = "or")
public class Or {

    @XmlElements({
        @XmlElement(name = "atomic", type = Atomic.class),
        @XmlElement(name = "not", type = Not.class),
        @XmlElement(name = "and", type = And.class),
        @XmlElement(name = "or", type = Or.class),
        @XmlElement(name = "imply", type = Imply.class),
        @XmlElement(name = "forall", type = Forall.class),
        @XmlElement(name = "exists", type = Exists.class)
    })
    protected List<Object> atomicOrNotOrAnd;

    /**
     * Gets the value of the atomicOrNotOrAnd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the atomicOrNotOrAnd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAtomicOrNotOrAnd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Atomic }
     * {@link Not }
     * {@link And }
     * {@link Or }
     * {@link Imply }
     * {@link Forall }
     * {@link Exists }
     * 
     * 
     */
    public List<Object> getAtomicOrNotOrAnd() {
        if (atomicOrNotOrAnd == null) {
            atomicOrNotOrAnd = new ArrayList<Object>();
        }
        return this.atomicOrNotOrAnd;
    }

}
